### ISSUE TITLE
Create Homepage

### ISSUE THREAD

**Issue by Benohene** [Joao4569/Hack_team_1#24]
EPIC: UX and design

As a **User** I can **access the homepage first** so that **I can be introduced to the site**.

**Acceptance Criteria**
- [ ]Have a Navigation Bar on the page
- [ ] Have a hero section an image with welcome text and a footer
- [ ] Tasks moved to the done column on the Kanban board

**Tasks**
- [ ] Create Responsive Navigation tabs for the site header
- [ ] Create Hero section content
- [ ] Create a video section and map link image
- [ ] Create a Footer with social links and partner links
